---

services:
  mosquitto:
    image: eclipse-mosquitto:2-openssl
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
